export const FETCH_ROUTES = "FETCH_ROUTES";
export const GET_SUB_ROUTE_IN_ORIGINAL_ROUTES =
  "GET_SUB_ROUTE_IN_ORIGINAL_ROUTES";
export const GET_ALL_ROUTES = "GET_ALL_ROUTES";

export const PROCESSING_ROUTING = "PROCESSING_ROUTING";

export const ROUTE_NUMBER_PROCESSED = "ROUTE_NUMBER_PROCESSED";

export const FETCH_ROUTES_DRIVERS_ORDERS = "FETCH_ROUTERS_DRIVERS_ORDERS";

export const GET_ROUTES_FROM_RANDOM_ORDERS = "GET_ROUTES_FROM_RANDOM_ORDERS";
