export const FETCH_ROUTES = "FETCH_ROUTES";
export const GET_SUB_ROUTE_IN_ORIGINAL_ROUTES =
  "GET_SUB_ROUTE_IN_ORIGINAL_ROUTES";
export const GET_ALL_ROUTES = "GET_ALL_ROUTES";

export const PROCESSING_ROUTING = "PROCESSING_ROUTING";
export const COMPLETE_PROCESSING_ROUTING = "COMPLETE_PROCESSING_ROUTING";

export const ROUTE_NUMBER_PROCESSED = "ROUTE_NUMBER_PROCESSED";
