const fConstants = {
    LOAD_CORDINATING_DATA: "LOAD_CORDINATING_DATA",
    SELECT_CUSTOMER: "SELECT_CUSTOMER",
    SCROLL_TIMELINE: "SCROLL_TIMELINE",
    ZOOM_TIMELINE: "ZOOM_TIMELINE",
    FETCH_INITIAL_DATA: "FETCH_INITIAL_DATA",
    FETCH_CHANGE_TIMELIME:"FETCH_CHANGE_TIMELIME",
    FETCH_CHANGE_RouteTabl:"FETCH_CHANGE_RouteTabl",
    SORT_TAI_XE:"SORT_TAI_XE",
    CHOSE_CUSTOMMER:"CHOSE_CUSTOMMER",
    CHOSE_CUSTOMMER_CTRL:"CHOSE_CUSTOMMER_CTRL"
  };
  
  export default fConstants;