const fConstants = {
  LOAD_CORDINATING_DATA: "LOAD_CORDINATING_DATA",
  SELECT_CUSTOMER: "SELECT_CUSTOMER",
  SCROLL_TIMELINE: "SCROLL_TIMELINE",
  ZOOM_TIMELINE: "ZOOM_TIMELINE"
};

export default fConstants;
